config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: %i[index show new create destroy] do
    resources :doses, only: %i[new create]
  end
  resources :doses, only: [:destroy]

  root to: 'cocktails#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail, presence: true, uniqueness: { scope: :ingredient}
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController

  before_action :find_cocktail_id, only: %i[edit show destroy]

  def index
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

    if @cocktail.save
      redirect_to @cocktail
    else
      render :new
    end
  end

  def new
    @cocktail = Cocktail.new
  end

  def edit
  end

  def show
  end


  def destroy
    @cocktail.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail_id
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController

  before_action :find_cocktail_id, only: %i[create new destroy]

  def index
    @doses = Dose.all
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save
      redirect_to @dose.cocktail
    else
      render :new
    end
  end

  def new
    @dose = Dose.new
  end

  def destroy
    @dose = dose.find(params[:id])
    @dose.destroy
    redirect_to cocktails_path
  end

  private

  def find_cocktail_id
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(cocktail) do |f| %>
  <%= f.input :name %>
  <%= f.input :photo, as: :file %>
  <%= f.submit "Save", class: "btn btn-primary" %>
<% end %>

app/views/cocktails/index.html.erb
<div class="container pad20">
    <!-- Grid row -->
  <div class="row mt-4">
    <!-- Card -->
    <% @cocktails.each do |cocktail| %>
      <% if cocktail.photo.attached? %>
        <% image_path = cl_image_path cocktail.photo.key %>
      <% else %>
        <% image_list = ['https://picsum.photos/200/300/?random=1', 'https://picsum.photos/200/300/?random=2' ,'https://picsum.photos/200/300/?random=3', 'https://picsum.photos/200/300/?random=4', 'https://picsum.photos/200/300/?random=5'] %>
        <% image_path = image_list.sample %>
      <% end %>
      
      <div class="col-xs-12 col-sm-4 py-2">
        <%= link_to cocktail_path(cocktail), class: "card-link" do %>
          <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)), url('<%= image_path %>')">
              <span><%= cocktail.name %></span>
          </div>
        <% end %>
      </div>
    <% end %>
  </div>


<!-- Close main div -->
</div>

app/views/cocktails/new.html.erb
<div class="container mt-4">
  <div class="row">
    <%= render 'form', cocktail: @cocktail %>
  </div>
</div>

app/views/cocktails/show.html.erb
<section>
  <div class="container">
    <div class="title">
      
      <div class="row">
        <div class="col-sm-12 col-lg-2">
        </div>
        <div class="col-sm-12 col-lg-4">
          <%= link_to new_cocktail_dose_path(@cocktail) do %>
            <i class="far fa-plus-square fa-border fa-sm"></i>  
          <% end %>

          <% if @cocktail.photo.attached? %>
            <% image_path = cl_image_path @cocktail.photo.key %>
          <% else %>
            <% image_path = 'https://picsum.photos/200/300?blur' %>
          <% end %>

          <%= link_to "", cocktail_path(@cocktail), method: :delete, data: { confirm: "Are you sure?" }, class: "far fa-trash-alt fa-sm ml-1 mr-2" %>
          <div class="card-show p-2" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.5)), url('<%= image_path %>')">
            <%= @cocktail.name %>
          </div>
        </div>

        <div class="col-sm-12 col-lg-2">
        </div>

        <div class="col-sm-12 col-lg-4">
          <h4 class="mt-2 text-center">Ingredients:</h4>
            <% iterator = 1 %>
            <% @cocktail.doses.each do |dose| %>
              <li><%= iterator %>) <%= dose.ingredient.name %></p>
              <li class="description"><i class="fas fa-angle-double-right fa-xs"></i><%= dose.description %></p>
              <% iterator +=1 %>
            <% end %>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/doses/new.html.erb
<h2>Add Ingredient</h2>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
    <%= f.association :ingredient %>
    <%= f.input :description %>
    <%= f.submit "Add", class: "btn btn-primary"%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    
    <style>@import url('https://fonts.googleapis.com/css2?family=Dancing+Script:wght@700&family=Dosis:wght@400&display=swap');</style>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-expand-sm navbar-light navbar-lewagon border border-shadow">
    <%= link_to cocktails_path, class: "navbar-brand" do %>
      <i class="fas fa-glass-martini-alt fa-lg ml-1"></i>
    <% end %>
      <!-- Add button -->
    <div class="">
      <%= link_to new_cocktail_path do %>
        <i class="fas fa-glass-cheers"> <span class="create">create</span></i>
      <% end %>
        
    </div>
    <h3 class="text-center main-navbar-head">Cocktails</h3>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    </div>

    <%= yield %>
  </body>
</html>